# .woodpecker.yml
pipeline:
  deps:
    image: node:12
    commands:
      - mkdir app
      - cp -r * /app
      - cp template.build /app/.env-cmdrc
      - WORKDIR /app
      - cd app
      - ls -la
      - npm install
      - yarn build:local
      - ls -la
    when:
      branch: develop