# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - BUILD_CONF="accelevir-prod"
      
      - if [ $BUILD_CONF == "local" ];
      - then BUNNY_DIR="/rm-lims-mirimus-com:"
      - build_script=$BUILD_CONF
      
      - elif [ $BUILD_CONF == "mirimus-qa" ];
      - then BUNNY_DIR="/rm-lims-mirimus-com:"
      - build_script="mirimus-qa"
      
      - elif [ $BUILD_CONF == "mirimus-prod" ];
      - then BUNNY_DIR="/rm-lims-mirimus-com:"
      - build_script="mirimus-prod"
      
      - elif [ $BUILD_CONF == "accelevir-prod" ];
      - then BUNNY_DIR="/rm-lims-mirimus-com:"
      - build_script="aclv"
      
      - elif [ $BUILD_CONF == "wynn-prod" ];
      - then BUNNY_DIR="/rm-lims-mirimus-com:"
      - build_script="wynn"
      
      - else
      - echo "Wrong build conf"
      - exit 1
      - fi;
      
      - node -v
      - cp template.build .env-cmdrc
      - npm install
      - npm rebuild node-sass
      - CI=false yarn build:$BUILD_CONF
      - cd build
      - ls -la
      #- echo $USER
      #- mkdir build
      #- cp template.build build/.env-cmdrc
      #- ls -la
    when:
       branch: develop
       event: push
  deploy:
    image: cschlosser/drone-ftps
    hostname: storage.bunnycdn.com:21
    secrets:
      - source: rm_bunny_username
        target: ftp_username
      - source: rm_bunny_password
        target: ftp_password
    src_dir:  /build
    dest_dir: $BUNNY_DIR 
    clean_dir: true
    chmod: false
    verify: false
    secure: false