# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - node -v
      - cp template.build .env-cmdrc
      - ls -la
      - npm install
      - npm rebuild node-sass
      - CI=false npm run build:local
    when:
      branch: develop