# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - npm install --legacy-peer-deps
      - yarn build:local
      - echo "test bild"
  when:
    event: push
    branch: develop