pipeline:
  build:
    image: node:14-alpine
    commands:
      - cd docs/
      - yarn install --frozen-lockfile
      - yarn build
      - echo "test bild"
  when:
    event: push
    branch: develop