# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - mkdir tmp
      - cp -r * tmp/
      - cp template.build tmp/.env-cmdrc
      - WORKDIR /tmp
      - cd app
      - ls -la
      - npm install
      - yarn build:local
      - ls -la
    when:
      branch: develop