# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - node -v
      - cp template.build .env-cmdrc
      - npm install
      - npm rebuild node-sass
      - CI=false yarn build:local
      - cd build
      - ls -la
  deploy:
    image: cschlosser/drone-ftps
    hostname: storage.bunnycdn.com:21
    secrets: [ rm_bunny_username, rm_bunny_password ]
    src_dir: build
    clean_dir: true
    chmod: false
    verify: false
    secure: false
   when:
     branch: develop