# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - node -v
# #     - cp template.build .env-cmdrc
# #     - npm install
# #     - npm rebuild node-sass
# #     - CI=false yarn build:local
#      - cd build
#      - ls -la
      - mkdir build
      - cp template.build build/.env-cmdrc
      - cd build
      - ls -la
  deploy:
    image: cschlosser/drone-ftps
    settings:
      hostname: storage.bunnycdn.com:21
      secrets: [ ftp_username, ftp_password ]     
    chmod: false
    verify: false
    secure: false
    
    