# .woodpecker.yml
pipeline:
  deps:
    image: node:12
    commands:
      - WORKDIR /srv/Projects/lims-frontend/tmp
      - npm install --legacy-peer-deps
      - yarn build:local
    when:
      branch: develop