# .woodpecker.yml
pipeline:
  deps:
    image: node:12
    commands:
      - mkdir app
      - cp -a *.* app/
      - cp template.build app/.env-cmdrc
      - cd app
      - ls -la
      - npm install
      - yarn build:local
      - ls -la
    when:
      branch: develop