# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - mkdir apps
      - cp -r * apps/
      - cp template.build apps/.env-cmdrc
      - WORKDIR /apps
      - cd app
      - ls -la
      - npm install
      - yarn build:local
      - ls -la
    when:
      branch: develop