# .woodpecker.yml
pipeline:
  build:
    image: node:12
    commands:
      - BUNNY_DIR="rm-lims-mirimus-com"
      - node -v
      - cp template.build .env-cmdrc
      - npm install
      - npm rebuild node-sass
      - CI=false yarn build:local
      - cd build
      - ls -la
      #- echo $USER
      #- mkdir build
      #- cp template.build build/.env-cmdrc
      #- ls -la
    when:
       branch: develop
       event: push
  deploy:
    image: cschlosser/drone-ftps
    hostname: storage.bunnycdn.com:21
    secrets:
      - source: rm_bunny_username
        target: ftp_username
      - source: rm_bunny_password
        target: ftp_password
    src_dir:  /build
    dest_dir: $BUNNY_DIR 
    clean_dir: true
    chmod: false
    verify: false
    secure: false