const actions = {
  ON_RECIPIENT_DATA_CHANGE: 'campaign/ON_RECIPIENT_DATA_CHANGE',
  CREATE_RECIPIENT_REQUEST: 'campaign/CREATE_RECIPIENT_REQUEST',
  CREATE_RECIPIENT_SUCCESS: 'campaign/CREATE_RECIPIENT_SUCCESS',
  CREATE_RECIPIENT_FAILURE: 'campaign/CREATE_RECIPIENT_FAILURE',
  LOAD_RECIPIENT_REQUEST: 'campaign/LOAD_RECIPIENT_REQUEST',
  LOAD_RECIPIENT_SUCCESS: 'campaign/LOAD_RECIPIENT_SUCCESS',
  LOAD_RECIPIENT_FAILURE: 'campaign/LOAD_RECIPIENT_FAILURE',
}

export default actions
