const actions = {
  ON_RECIPIENT_DATA_CHANGE: 'recipient/ON_RECIPIENT_DATA_CHANGE',
  CREATE_RECIPIENT_REQUEST: 'recipient/CREATE_RECIPIENT_REQUEST',
  CREATE_RECIPIENT_SUCCESS: 'recipient/CREATE_RECIPIENT_SUCCESS',
  CREATE_RECIPIENT_FAILURE: 'recipient/CREATE_RECIPIENT_FAILURE',
  LOAD_RECIPIENTS_REQUEST: 'recipient/LOAD_RECIPIENTS_REQUEST',
  LOAD_RECIPIENTS_SUCCESS: 'recipient/LOAD_RECIPIENTS_SUCCESS',
  LOAD_RECIPIENTS_FAILURE: 'recipient/LOAD_RECIPIENTS_FAILURE',
  GET_RECIPIENT_REQUEST: 'recipient/GET_RECIPIENT_REQUEST',
  GET_RECIPIENT_SUCCESS: 'recipient/GET_RECIPIENT_SUCCESS',
  GET_RECIPIENT_FAILURE: 'recipient/GET_RECIPIENT_FAILURE',
  PUT_RECIPIENT_REQUEST: 'recipient/PUT_RECIPIENT_REQUEST',
  PUT_RECIPIENT_SUCCESS: 'recipient/PUT_RECIPIENT_SUCCESS',
  PUT_RECIPIENT_FAILURE: 'recipient/PUT_RECIPIENT_FAILURE',
};

export default actions;
