const run = {
  data: {
    status: 'review',
    items: [
      {
        id: 1,
        company_short: 'COMPANYSHORT',
        pool_name: 'M1',
        // pool_size: 24,
        sample_id: 'EQ12345678',
        result: 'Inconclusive',
        interpreted_result: 'Inconclusive',
        reflex_sc: true,
        reflex_sd: false,
        rerun: false,
        children: [
          {
            wells: 'A3',
            ms2: 27.27,
            ms2_msg: 'warning text',
            n_gene: 5.27,
            n_gene_msg: 'warning text',
            s_gene: 33.33,
            s_gene_msg: '',
            orf1ab: 1,
            orf1ab_msg: '',
            rp: 1,
            rp_msg: '',
          },
          {
            wells: 'A4',
            ms2: 27.27,
            ms2_msg: '',
            n_gene: 4.11,
            n_gene_msg: '',
            s_gene: 33.33,
            s_gene_msg: 'warning text',
            orf1ab: 1,
            orf1ab_msg: 'some warning text',
            rp: 1,
            rp_msg: 'warning text',
          },
          {
            wells: 'B4',
            ms2: 27.27,
            n_gene: 5.27,
            s_gene: 33.33,
          },
        ],
      },
      {
        id: 2,
        company_short: 'COMPANYSHORT',
        pool_name: 'M2',
        pool_size: 22,
        sample_id: 'EQ87654321',
        result: 'Not Detected',
        interpreted_result: 'Inconclusive',
        reflex_sc: false,
        reflex_sd: false,
        rerun: true,
        children: [
          {
            wells: 'A3',
            ms2: 27.27,
            n_gene: 5.27,
            s_gene: 33.33,
          },
          {
            wells: 'A4',
            ms2: 27.27,
            n_gene: 4.27,
            s_gene: 33.33,
          },
          {
            wells: 'B4',
            ms2: 27.27,
            n_gene: 4.27,
            s_gene: 33.33,
          },
        ],
      },
    ],
  },
};

export default run;
