export const activeWrapper: string;
export const brand: string;
export const circleWrapper: string;
export const info: string;
export const pulsatingCircle: string;
export const pulseDot: string;
export const pulseRing: string;
export const timer: string;
export const topbar: string;
