const actions = {
  FETCH_CREDENTIALS_REQUEST: 'hijack/FETCH_CREDENTIALS_REQUEST',
  FETCH_CREDENTIALS_SUCCESS: 'hijack/FETCH_CREDENTIALS_SUCCESS',
  FETCH_CREDENTIALS_FAILURE: 'hijack/FETCH_CREDENTIALS_FAILURE',
  LOGOUT: 'hijack/LOGOUT',
  RESTORE: 'hijack/RESTORE',
};

export default actions;
