const actions = {
  FETCH_BATCHES_REQUEST: 'batches/FETCH_BATCHES_REQUEST',
  FETCH_BATCHES_SUCCESS: 'batches/FETCH_BATCHES_SUCCESS',
  FETCH_BATCHES_FAILURE: 'batches/FETCH_BATCHES_FAILURE',
  PUBLISH_BATCH_REQUEST: 'batches/PUBLISH_BATCH_REQUEST',
  PUBLISH_BATCH_SUCCESS: 'batches/PUBLISH_BATCH_SUCCESS',
  PUBLISH_BATCH_FAILURE: 'batches/PUBLISH_BATCH_FAILURE',
};

export default actions;
