const actions = {
  FETCH_POOLS_BY_BATCH_ID_REQUEST: 'pools/FETCH_POOLS_BY_BATCH_ID_REQUEST',
  FETCH_POOLS_BY_BATCH_ID_SUCCESS: 'pools/FETCH_POOLS_BY_BATCH_ID_SUCCESS',
  FETCH_POOLS_BY_BATCH_ID_FAILURE: 'pools/FETCH_POOLS_BY_BATCH_ID_FAILURE',

  FETCH_POOLS_BY_COMPANY_ID_REQUEST: 'pools/FETCH_POOLS_BY_COMPANY_ID_REQUEST',
  FETCH_POOLS_BY_COMPANY_ID_SUCCESS: 'pools/FETCH_POOLS_BY_COMPANY_ID_SUCCESS',
  FETCH_POOLS_BY_COMPANY_ID_FAILURE: 'pools/FETCH_POOLS_BY_COMPANY_ID_FAILURE',

  PUBLISH_POOL_REQUEST: 'pools/PUBLISH_POOL_REQUEST',
  PUBLISH_POOL_SUCCESS: 'pools/PUBLISH_POOL_SUCCESS',
  PUBLISH_POOL_FAILURE: 'pools/PUBLISH_POOL_FAILURE',
};

export default actions;
