const actions = {
  FETCH_COMPANIES_REQUEST: 'intake/FETCH_COMPANIES_REQUEST',
  FETCH_COMPANIES_SUCCESS: 'intake/FETCH_COMPANIES_SUCCESS',
  FETCH_COMPANIES_FAILURE: 'intake/FETCH_COMPANIES_FAILURE',

  CREATE_PACKING_REQUEST: 'intake/CREATE_PACKING_REQUEST',
  CREATE_PACKING_SUCCESS: 'intake/CREATE_PACKING_SUCCESS',
  CREATE_PACKING_FAILURE: 'intake/CREATE_PACKING_FAILURE',
};

export default actions;
