const actions = {
  CREATE_PROJECT_REQUEST: 'env/CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: 'env/CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: 'env/CREATE_PROJECT_FAILURE',
};

export default actions;
