const actions = {
    ON_CAMPAIGN_DATA_CHANGE: 'campaign/ON_CAMPAIGN_DATA_CHANGE',
    CREATE_CAMPAIGN_REQUEST: 'campaign/CREATE_CAMPAIGN_REQUEST',
    CREATE_CAMPAIGN_SUCCESS: 'campaign/CREATE_CAMPAIGN_SUCCESS',
    CREATE_CAMPAIGN_FAILURE: 'campaign/CREATE_CAMPAIGN_FAILURE',
    LOAD_CAMPAIGN_REQUEST: 'campaign/LOAD_CAMPAIGN_REQUEST',
    LOAD_CAMPAIGN_SUCCESS: 'campaign/LOAD_CAMPAIGN_SUCCESS',
    LOAD_CAMPAIGN_FAILURE: 'campaign/LOAD_CAMPAIGN_FAILURE',
  }


  export default actions
