const actions = {
  ON_CAMPAIGN_DATA_CHANGE: 'campaign/ON_CAMPAIGN_DATA_CHANGE',

  CREATE_CAMPAIGN_REQUEST: 'campaign/CREATE_CAMPAIGN_REQUEST',
  CREATE_CAMPAIGN_SUCCESS: 'campaign/CREATE_CAMPAIGN_SUCCESS',
  CREATE_CAMPAIGN_FAILURE: 'campaign/CREATE_CAMPAIGN_FAILURE',

  LOAD_CAMPAIGN_REQUEST: 'campaign/LOAD_CAMPAIGN_REQUEST',
  LOAD_CAMPAIGN_SUCCESS: 'campaign/LOAD_CAMPAIGN_SUCCESS',
  LOAD_CAMPAIGN_FAILURE: 'campaign/LOAD_CAMPAIGN_FAILURE',

  REMOVE_CAMPAIGN_REQUEST: 'campaign/REMOVE_CAMPAIGN_REQUEST',
  REMOVE_CAMPAIGN_SUCCESS: 'campaign/REMOVE_CAMPAIGN_SUCCESS',
  REMOVE_CAMPAIGN_FAILURE: 'campaign/REMOVE_CAMPAIGN_FAILURE',

  START_CAMPAIGN_REQUEST: 'campaign/START_CAMPAIGN_REQUEST',
  START_CAMPAIGN_SUCCESS: 'campaign/START_CAMPAIGN_SUCCESS',
  START_CAMPAIGN_FAILURE: 'campaign/START_CAMPAIGN_FAILURE',

  GET_CAMPAIGN_REQUEST: 'campaign/GET_CAMPAIGN_REQUEST',
  GET_CAMPAIGN_SUCCESS: 'campaign/GET_CAMPAIGN_SUCCESS',
  GET_CAMPAIGN_FAILURE: 'campaign/GET_CAMPAIGN_FAILURE',

  GET_CAMPAIGN_STATISTICS_REQUEST: 'campaign/GET_CAMPAIGN_STATISTICS_REQUEST',
  GET_CAMPAIGN_STATISTICS_SUCCESS: 'campaign/GET_CAMPAIGN_STATISTICS_SUCCESS',
  GET_CAMPAIGN_STATISTICS_FAILURE: 'campaign/GET_CAMPAIGN_STATISTICS_FAILURE',
};

export default actions;
