const actions = {
  SET_STATE: 'user/SET_STATE',
  LOGIN_REQUEST: 'user/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'user/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'user/LOGIN_FAILURE',
  RESTORE_REQUEST: 'user/RESTORE_REQUEST',
  RESTORE_SUCCESS: 'user/RESTORE_SUCCESS',
  RESTORE_FAILURE: 'user/RESTORE_FAILURE',
  LOGOUT: 'user/LOGOUT',
  FETCH_USERS_REQUEST: 'user/FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'user/FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'user/FETCH_USERS_FAILURE',
};

export default actions;
