export const infiniteLoadingIcon: string;
export const mobileTableHeaderRow: string;
export const mobileTableHeaderWrapper: string;
export const modalButton: string;
export const pageHeader: string;
export const search: string;
export const tableActionsWrapper: string;
export const tableHeader: string;
export const tabletActionsWrapper: string;
