const actions = {
  FETCH_ENVIROMENT_REQUEST: 'env/FETCH_ENVIROMENT_REQUEST',
  FETCH_ENVIROMENT_SUCCESS: 'env/FETCH_ENVIROMENT_SUCCESS',
  FETCH_ENVIROMENT_FAILURE: 'env/FETCH_ENVIROMENT_FAILURE',

  CREATE_ENVIROMENT_REQUEST: 'env/CREATE_ENVIROMENT_REQUEST',
  CREATE_ENVIROMENT_SUCCESS: 'env/CREATE_ENVIROMENT_SUCCESS',
  CREATE_ENVIROMENT_FAILURE: 'env/CREATE_ENVIROMENT_FAILURE',
};

export default actions;
